version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: |
        mongosh --eval "
          if (!rs.isMaster().ismaster) {
            rs.initiate({
              _id: 'rs0',
              members: [{ _id: 0, host: 'localhost:27017' }]
            });
          }"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  t3-app:
    build:
      context: ./
    container_name: t3-app
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      DATABASE_URL: "mongodb://mongodb:27017/mydatabase?replicaSet=rs0"
    volumes:
      - ./:/app
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:
    driver: bridge