version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - mynetwork
    command: ["mongod", "--replSet", "rs0"]

  t3-app:
    build:
      context: ./  # Adjust this path to your T3 app directory
    container_name: t3-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: "mongodb://mongodb:27017/mydatabase"  # This matches the MongoDB service name
    volumes:
      - ./:/app  # Mount the current directory to /app in the container
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:
